apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescaledb-postgis-standard-trixie
  labels:
    images.cnpg.io/family: timescaledb-postgis
    images.cnpg.io/type: standard
    images.cnpg.io/os: trixie
    images.cnpg.io/date: '20260827'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
  - major: 15
    image: ghcr.io/try2codesecure/timescaledb-postgis:15.19-3.6.4-202608271733-standard-trixie@sha256:e679df7fd8074b8e68566f913a61ee32379a8004425df09df2db14d95b30ecfd
  - major: 16
    image: ghcr.io/try2codesecure/timescaledb-postgis:16.15-3.6.4-202608271733-standard-trixie@sha256:38c4cec1bbb61cd3c128db4e961684c6383e82edab0ae09ad4e1a198d8be51d7
  - major: 17
    image: ghcr.io/try2codesecure/timescaledb-postgis:17.11-3.6.4-202608271733-standard-trixie@sha256:cc6a0d4c44d4ac458b845a98a4e6de5af460ff73650646c98341e3a13e40bdcb
  - major: 18
    image: ghcr.io/try2codesecure/timescaledb-postgis:18.6-3.6.4-202608271733-standard-trixie@sha256:399992fb3e7cf0dccb6bdbcddd4f681df8f95ac122425e71bcebf2d28100b3c3
