apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: timescaledb-postgis-standard-trixie
  labels:
    images.cnpg.io/family: timescaledb-postgis
    images.cnpg.io/type: standard
    images.cnpg.io/os: trixie
    images.cnpg.io/date: '20260907'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
  - major: 15
    image: ghcr.io/try2codesecure/timescaledb-postgis:15.19-3.6.4-202609071530-standard-trixie@sha256:e0b815e3befad3e7069aa72ef9d3b66fbb50f84b18053ced9ec4a4e4bfec8c49
  - major: 16
    image: ghcr.io/try2codesecure/timescaledb-postgis:16.15-3.6.4-202609071530-standard-trixie@sha256:082e2ef25ab319d3c696e0455dbf21a4aa3f0766eb9e584245cc6056e9ab0edb
  - major: 17
    image: ghcr.io/try2codesecure/timescaledb-postgis:17.11-3.6.4-202609071530-standard-trixie@sha256:a941ced0307963b9c82d9c30373179ebf69a4d5a01a7aa3cab61877cf8e1bf86
  - major: 18
    image: ghcr.io/try2codesecure/timescaledb-postgis:18.6-3.6.4-202609071530-standard-trixie@sha256:97cfdceadb25b716f9846f15c2c0df3b88b5adf1c831804e29d2098628c7767c
